### ISSUE TITLE
Remove deprecated function calls

### ISSUE THREAD

**Issue by espottesmith** [materialsproject/mrnet#9]
A recent PR changed several function names in mol_entry.py for the MoleculeEntry class. This inlcudes:

free_energy -> get_free_energy
Nbonds -> num_bonds
edges -> bonds

These are currently causing an aggressive quantity of deprecation warnings, which makes reading output difficult. It would be immensely helpful if someone would go through and change these outdated function calls throughout the repo.

**Comment by mjwen** [comment]
I can do it.

In the previous PR, I did not do it because a lot of tests rely on these. So, I still hope somebody can rewrite the tests before doing this (I am not super familiar with UnitTest and do not want to deal with it). 

Also, I will probably make modifications to mol_entry to make the input energy, enthalpy, entropy be of units eV, instead of the present ones.  And some other TODOs I left there. 

But, if we do not care too much about the current tests and allow it to fail (since we are making huge changes), I can do it right away.

**Comment by mjwen** [comment]
Well, looking at the PR I just made, I realize that the tests will definitely fail since MoleculeEntry used to be in pymatgen. So, I guess I will do it right away.

**Comment by espottesmith** [comment]
I'm happy to lead the charge on converting from unittest to pytest. I just want to wait until all of the tests pass before doing so.
